import = ["/home/from/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"
